apiVersion: v1
kind: Pod
metadata:
  name: app
  namespace: app
  labels:
    manifestType: pod
    app: employee
spec:
  containers:
  - name: app
    image: docker.io/library/my-app:v1.0
    env:
      - name: DBHOST
        value: <dbhost-ip>
      - name: DBPORT
        value: "3306"
      - name: DATABASE
        value: "employees"
      - name: DBPWD
        valueFrom:
          secretKeyRef:
            name: mysql-credentials
            key: password
      - name: DBUSER
        valueFrom:
          secretKeyRef:
            name: mysql-credentials
            key: user
      - name: APP_COLOR
        value: "blue"
    ports:
    - containerPort: 80
  dnsPolicy: ClusterFirst
  restartPolicy: Always
